"""
NeuronPath Global Learning Catalog
Defines comprehensive skills, prerequisites, high-quality learning resources, and role presets
across Programming, Data/AI, Software Development, Cloud/DevOps, Computer Science, and Tech Specializations.
"""

CATALOG_SKILLS = [
    # --- PROGRAMMING LANGUAGES ---
    {"name": "Python Basics", "category": "Programming", "description": "variables, data types, operators, conditionals, loops, functions, basic collections, input/output, exceptions basics"},
    {"name": "Python Intermediate", "category": "Programming", "description": "OOP, decorators, generators, iterators, comprehensions, modules/packages, context managers, testing, typing, advanced exception handling"},
    {"name": "Python Advanced", "category": "Programming", "description": "concurrency/asyncio, multiprocessing, performance optimization, memory management, advanced architecture/patterns, metaprogramming, profiling, production-grade Python"},
    {"name": "Java Fundamentals", "category": "Programming", "description": "Java syntax, JVM architecture, data types, control structures, methods"},
    {"name": "Java OOP & Collections", "category": "Programming", "description": "Inheritance, polymorphism, interfaces, Generics, List, Map, Set collections"},
    {"name": "Spring Boot & Enterprise Java", "category": "Programming", "description": "Dependency injection, Spring MVC, REST APIs, Spring Data JPA"},
    {"name": "C Programming Basics", "category": "Programming", "description": "C syntax, compilation pipeline, control flow, functions, standard I/O"},
    {"name": "Pointers & Memory Management", "category": "Programming", "description": "Pointers, dynamic memory allocation (malloc/free), structs, memory layout"},
    {"name": "C++ Fundamentals", "category": "Programming", "description": "C++ syntax, classes, references, operator overloading, templates"},
    {"name": "Modern C++ & STL", "category": "Programming", "description": "Smart pointers, lambda expressions, RAII, STL vectors, algorithms, C++17/20"},
    {"name": "C# Basics & OOP", "category": "Programming", "description": "C# language syntax, class hierarchies, LINQ, properties, delegates, events"},
    {"name": ".NET Core & ASP.NET", "category": "Programming", "description": "ASP.NET Core Web APIs, Entity Framework Core, middleware, dependency injection"},
    {"name": "JavaScript Fundamentals", "category": "Programming", "description": "JS syntax, variables, data types, operators, conditionals, loops, functions, arrays, objects"},
    {"name": "JavaScript Essentials", "category": "Programming", "description": "JS syntax, DOM manipulation, closures, events, prototypes"},
    {"name": "Modern ES6+ & Async JS", "category": "Programming", "description": "Arrow functions, destructuring, promises, async/await, modules, fetch API, event loop"},
    {"name": "TypeScript Fundamentals", "category": "Programming", "description": "Static typing, interfaces, type aliases, union types, tsconfig"},
    {"name": "Advanced TypeScript", "category": "Programming", "description": "Generics, utility types, mapped types, conditional types, declaration files"},
    {"name": "Go Fundamentals", "category": "Programming", "description": "Go syntax, packages, structs, interfaces, slices, error handling"},
    {"name": "Go Concurrency & Goroutines", "category": "Programming", "description": "Goroutines, channels, select statements, sync package, worker pools"},
    {"name": "Rust Syntax & Ownership", "category": "Programming", "description": "Rust borrowing, ownership model, lifetimes, pattern matching, enums"},
    {"name": "Rust Concurrency & Cargo", "category": "Programming", "description": "Threads, channels, traits, error handling with Result, Cargo packages"},
    {"name": "Kotlin Basics", "category": "Programming", "description": "Kotlin syntax, null safety, data classes, extension functions, lambdas"},
    {"name": "Swift Syntax & Basics", "category": "Programming", "description": "Swift fundamentals, optionals, protocols, structs vs classes, closures"},
    {"name": "R for Statistical Computing", "category": "Programming", "description": "R data frames, vectors, statistical functions, data manipulation"},
    {"name": "Tidyverse & ggplot2", "category": "Programming", "description": "dplyr, tidyr, data wrangling, grammar of graphics with ggplot2"},
    {"name": "PHP Fundamentals", "category": "Programming", "description": "PHP syntax, superglobals, sessions, forms, database PDO connection"},
    {"name": "Laravel Framework", "category": "Programming", "description": "Routing, Blade templates, Eloquent ORM, migrations, middleware, authentication"},

    # --- DATA & AI ---
    {"name": "SQL Fundamentals", "category": "Data", "description": "SELECT, WHERE, JOINs, GROUP BY, subqueries, table schemas"},
    {"name": "SQL Advanced", "category": "Data", "description": "Window functions, CTEs, query optimization, indexing, stored procedures"},
    {"name": "Linear Algebra", "category": "Math & Statistics", "description": "Vectors, matrices, eigenvalues, dot products, matrix decomposition"},
    {"name": "Calculus", "category": "Math & Statistics", "description": "Derivatives, integrals, gradients, chain rule, optimization"},
    {"name": "Probability", "category": "Math & Statistics", "description": "Probability distributions, Bayes theorem, conditional probability, expectation"},
    {"name": "Descriptive Statistics", "category": "Math & Statistics", "description": "Mean, median, variance, standard deviation, IQR, percentiles"},
    {"name": "Inferential Statistics", "category": "Math & Statistics", "description": "Hypothesis testing, confidence intervals, p-values, ANOVA, t-tests"},
    {"name": "NumPy", "category": "Data", "description": "Array operations, broadcasting, vectorization, linear algebra with NumPy"},
    {"name": "Pandas", "category": "Data", "description": "DataFrames, data cleaning, merging, grouping, time series analysis"},
    {"name": "Data Visualization", "category": "Data", "description": "Matplotlib, Seaborn, interactive charting, visual communication"},
    {"name": "Data Cleaning", "category": "Data", "description": "Handling missing values, outliers, data type conversions, validation"},
    {"name": "Exploratory Data Analysis", "category": "Data", "description": "Statistical summaries, distribution analysis, correlation matrices, patterns"},
    {"name": "ETL Pipelines & Data Warehousing", "category": "Data", "description": "Data ingestion pipelines, dbt, Snowflake, schema star/snowflake modeling"},
    {"name": "Apache Spark & Distributed Computing", "category": "Data", "description": "PySpark, RDDs, DataFrames, streaming data, distributed data processing"},
    {"name": "Power BI & Tableau Dashboarding", "category": "Data", "description": "Business reporting, interactive KPI dashboards, DAX formulas, data blending"},
    {"name": "ML Fundamentals", "category": "Machine Learning", "description": "Supervised vs unsupervised learning, bias-variance tradeoff, cross-validation"},
    {"name": "Linear & Logistic Regression", "category": "Machine Learning", "description": "Regression models, cost functions, gradient descent, classification metrics"},
    {"name": "Decision Trees & Ensemble Methods", "category": "Machine Learning", "description": "Random Forests, XGBoost, LightGBM, feature importance, bagging & boosting"},
    {"name": "Model Evaluation & Tuning", "category": "Machine Learning", "description": "ROC-AUC, Precision-Recall, F1-score, GridSearchCV, Hyperopt"},
    {"name": "Feature Engineering", "category": "Machine Learning", "description": "Categorical encoding, feature scaling, polynomial features, dimensionality reduction"},
    {"name": "Neural Networks Basics", "category": "Machine Learning", "description": "Perceptrons, activation functions, backpropagation, loss functions"},
    {"name": "Deep Learning with PyTorch", "category": "Machine Learning", "description": "Tensors, autograd, nn.Module, training loops, GPU acceleration"},
    {"name": "Computer Vision & CNNs", "category": "Machine Learning", "description": "Convolutional layers, OpenCV, image classification, object detection"},
    {"name": "Natural Language Processing", "category": "Machine Learning", "description": "Tokenization, embeddings, sentiment analysis, text classification"},
    {"name": "Transformers & LLM Engineering", "category": "Machine Learning", "description": "Attention mechanism, HuggingFace, fine-tuning, prompt engineering, RAG"},
    {"name": "Vector Databases & Semantic Search", "category": "Machine Learning", "description": "Pinecone, ChromaDB, embeddings, cosine similarity, hybrid search"},

    # --- SOFTWARE & WEB DEVELOPMENT ---
    {"name": "HTML Fundamentals", "category": "Web Development", "description": "Semantic HTML5, markup structure, elements, attributes, forms, accessibility basics"},
    {"name": "CSS Fundamentals", "category": "Web Development", "description": "CSS selectors, cascade, specificity, box model, colors, typography, border-box"},
    {"name": "Responsive Design & CSS Layouts", "category": "Web Development", "description": "Flexbox, CSS Grid, media queries, mobile-first responsive design"},
    {"name": "HTML & CSS Responsive Layouts", "category": "Web Development", "description": "Semantic HTML5, Flexbox, CSS Grid, responsive media queries, Tailwind CSS"},
    {"name": "DOM & Browser APIs", "category": "Web Development", "description": "DOM manipulation, event listeners, bubbling/capturing, LocalStorage, Web APIs"},
    {"name": "Git & Version Control", "category": "Software Engineering", "description": "Branching, merging, pull requests, rebase, Git workflows"},
    {"name": "React Fundamentals", "category": "Web Development", "description": "JSX syntax, components, props, conditional rendering, list keys"},
    {"name": "React State & Hooks", "category": "Web Development", "description": "useState, useEffect, custom hooks, context API, state lifting"},
    {"name": "React & State Management", "category": "Web Development", "description": "Components, JSX, hooks, useEffect, context, Redux/Zustand"},
    {"name": "Backend Development", "category": "Web Development", "description": "Node.js runtime, Express server, routing, middleware, request/response cycle"},
    {"name": "RESTful API Design", "category": "Software Engineering", "description": "HTTP methods, status codes, resource endpoints, OpenAPI/Swagger"},
    {"name": "Databases & SQL", "category": "Software Engineering", "description": "Relational database modeling, CRUD queries, primary/foreign keys, joins, migrations"},
    {"name": "Authentication & Web Security", "category": "Software Engineering", "description": "JWT tokens, password hashing with bcrypt, sessions, CORS, XSS/CSRF prevention"},
    {"name": "GraphQL APIs", "category": "Software Engineering", "description": "Schema definition, queries, mutations, resolvers, Apollo Client"},
    {"name": "Microservices Architecture", "category": "Software Engineering", "description": "Service decomposition, event-driven architecture, API Gateways, message queues"},
    {"name": "Full-Stack Project Architecture", "category": "Web Development", "description": "End-to-end integration, client state management, database schema design, capstone delivery"},
    {"name": "Cross-Platform Flutter & Dart", "category": "Mobile Development", "description": "Flutter widgets, state management (Bloc/Provider), Dart programming"},
    {"name": "Android Development with Kotlin", "category": "Mobile Development", "description": "Jetpack Compose, Android lifecycle, Activities, ViewModel, Room DB"},
    {"name": "iOS Development with SwiftUI", "category": "Mobile Development", "description": "SwiftUI views, state binding, navigation, CoreData, Xcode"},
    {"name": "Unity & C# Game Scripting", "category": "Game Development", "description": "Unity GameObjects, components, physics, collision detection, C# scripts"},
    {"name": "Unreal Engine & C++", "category": "Game Development", "description": "Unreal Engine blueprints, C++ gameplay architecture, rendering, physics"},
    {"name": "Software Design Patterns", "category": "Software Engineering", "description": "Factory, Singleton, Observer, Strategy, SOLID principles, clean code"},
    {"name": "Test Automation & QA", "category": "Software Engineering", "description": "Unit testing, integration testing, Selenium, Playwright, PyTest/Jest"},

    # --- CLOUD & DEVOPS ---
    {"name": "Linux Command Line", "category": "Software Engineering", "description": "Bash scripting, process management, permissions, file systems"},
    {"name": "Docker Basics", "category": "DevOps", "description": "Containers, Dockerfiles, images, volume mounting, Docker Compose"},
    {"name": "Container Networking & Storage", "category": "DevOps", "description": "Docker bridge networks, volumes, tmpfs, multi-container communication"},
    {"name": "Kubernetes Orchestration", "category": "DevOps", "description": "Pods, Deployments, Services, ConfigMaps, Ingress, Helm charts"},
    {"name": "CI/CD Pipelines", "category": "DevOps", "description": "GitHub Actions, GitLab CI, automated testing, continuous deployment"},
    {"name": "Infrastructure as Code (Terraform)", "category": "DevOps", "description": "HCL syntax, providers, state management, resource provisioning"},
    {"name": "AWS Cloud Foundations", "category": "Cloud", "description": "EC2, S3, IAM, VPC, Lambda, RDS, CloudWatch, AWS CLI"},
    {"name": "Microsoft Azure Foundations", "category": "Cloud", "description": "Azure VMs, Blob Storage, Azure AD, App Services, Virtual Networks"},
    {"name": "Google Cloud Platform (GCP)", "category": "Cloud", "description": "Compute Engine, Cloud Storage, Cloud Run, GKE, BigQuery"},
    {"name": "Site Reliability & Monitoring", "category": "DevOps", "description": "SLOs/SLAs, Prometheus, Grafana, alerting, incident response, logging"},
    {"name": "Deployment & DevOps", "category": "DevOps", "description": "Docker containerization, environment variables, reverse proxies, CI/CD automation"},
    {"name": "Model Deployment & MLOps", "category": "MLOps", "description": "FastAPI ML serving, model registries, MLflow, Docker deployment for AI"},

    # --- COMPUTER SCIENCE & SECURITY ---
    {"name": "Data Structures (Arrays, Lists, Trees)", "category": "Computer Science", "description": "Arrays, linked lists, stacks, queues, binary search trees, heaps"},
    {"name": "Algorithms (Sorting, Searching, Graphs)", "category": "Computer Science", "description": "Binary search, quicksort, BFS/DFS, Dijkstra, dynamic programming"},
    {"name": "System Design Fundamentals", "category": "Computer Science", "description": "Load balancers, caching (Redis), CDN, database sharding, CAP theorem"},
    {"name": "Computer Networks & Protocols", "category": "Computer Science", "description": "TCP/IP, UDP, DNS, HTTP/HTTPS, SSL/TLS, socket programming"},
    {"name": "Operating Systems & Concurrency", "category": "Computer Science", "description": "Processes, threads, mutexes, virtual memory, scheduling algorithms"},
    {"name": "Network Security & Cryptography", "category": "Cybersecurity", "description": "Symmetric/asymmetric encryption, firewalls, VPNs, hashing, PKI"},
    {"name": "Ethical Hacking & Web Security", "category": "Cybersecurity", "description": "OWASP Top 10, SQL injection, XSS, penetration testing, Burp Suite"},
    {"name": "Security Auditing & Hardening", "category": "Cybersecurity", "description": "Linux system hardening, vulnerability scanning, security compliance, SIEM"},

    # --- SPECIALIZATIONS (BLOCKCHAIN, IOT, PRODUCT, UX) ---
    {"name": "Solidity & Smart Contracts", "category": "Blockchain", "description": "Solidity syntax, EVM, ERC-20, ERC-721 tokens, smart contract security"},
    {"name": "Web3 & Decentralized Apps", "category": "Blockchain", "description": "Ethers.js, Web3.js, MetaMask integration, IPFS, decentralized frontend"},
    {"name": "Embedded Systems & Microcontrollers", "category": "Hardware & IoT", "description": "C/C++ for Arduino/STM32, GPIO, I2C, SPI, UART, registers"},
    {"name": "IoT Protocols & Edge Computing", "category": "Hardware & IoT", "description": "MQTT protocol, Raspberry Pi, sensor integration, telemetry streaming"},
    {"name": "Robotics & ROS", "category": "Robotics", "description": "Robot Operating System (ROS2), kinematics, sensor fusion, navigation stack"},
    {"name": "UI/UX Design & Wireframing", "category": "Product & Design", "description": "User journey mapping, wireframing, typography, color theory, user research"},
    {"name": "Figma & Design Systems", "category": "Product & Design", "description": "Figma auto-layout, components, interactive prototyping, design tokens"},
    {"name": "Product Strategy & Management", "category": "Product & Design", "description": "Product roadmaps, user stories, sprint planning, OKRs, KPI metrics"},
    {"name": "Technical Communication", "category": "Soft Skills", "description": "Engineering documentation, code reviews, technical presentations, specs"},
    {"name": "Problem Formulation", "category": "Soft Skills", "description": "Deconstructing business problems, requirements analysis, success metrics"},
]

# (skill_name, prerequisite_name, strength)
CATALOG_PREREQUISITES = [
    # Web & Full Stack
    ("CSS Fundamentals", "HTML Fundamentals", 1.0),
    ("Responsive Design & CSS Layouts", "CSS Fundamentals", 1.0),
    ("HTML & CSS Responsive Layouts", "HTML Fundamentals", 1.0),
    ("JavaScript Fundamentals", "HTML Fundamentals", 0.9),
    ("JavaScript Essentials", "HTML Fundamentals", 0.9),
    ("Modern ES6+ & Async JS", "JavaScript Fundamentals", 1.0),
    ("Modern ES6+ & Async JS", "JavaScript Essentials", 1.0),
    ("DOM & Browser APIs", "Modern ES6+ & Async JS", 1.0),
    ("React Fundamentals", "Modern ES6+ & Async JS", 1.0),
    ("React State & Hooks", "React Fundamentals", 1.0),
    ("React & State Management", "React Fundamentals", 1.0),
    ("Backend Development", "JavaScript Fundamentals", 0.9),
    ("RESTful API Design", "Backend Development", 1.0),
    ("Databases & SQL", "Backend Development", 0.9),
    ("Authentication & Web Security", "RESTful API Design", 0.9),
    ("Test Automation & QA", "React State & Hooks", 0.8),
    ("Deployment & DevOps", "Git & Version Control", 0.8),
    ("Full-Stack Project Architecture", "Authentication & Web Security", 0.9),
    ("Full-Stack Project Architecture", "Deployment & DevOps", 0.9),

    # Programming
    ("Python Intermediate", "Python Basics", 1.0),
    ("Python Advanced", "Python Intermediate", 1.0),
    ("Java OOP & Collections", "Java Fundamentals", 1.0),
    ("Spring Boot & Enterprise Java", "Java OOP & Collections", 0.9),
    ("Pointers & Memory Management", "C Programming Basics", 1.0),
    ("C++ Fundamentals", "C Programming Basics", 0.8),
    ("Modern C++ & STL", "C++ Fundamentals", 1.0),
    (".NET Core & ASP.NET", "C# Basics & OOP", 1.0),
    ("TypeScript Fundamentals", "JavaScript Fundamentals", 0.9),
    ("Advanced TypeScript", "TypeScript Fundamentals", 1.0),
    ("Go Concurrency & Goroutines", "Go Fundamentals", 1.0),
    ("Rust Concurrency & Cargo", "Rust Syntax & Ownership", 1.0),
    ("Android Development with Kotlin", "Kotlin Basics", 0.9),
    ("iOS Development with SwiftUI", "Swift Syntax & Basics", 0.9),
    ("Tidyverse & ggplot2", "R for Statistical Computing", 1.0),
    ("Laravel Framework", "PHP Fundamentals", 1.0),

    # Data & AI
    ("SQL Advanced", "SQL Fundamentals", 1.0),
    ("NumPy", "Python Basics", 1.0),
    ("Pandas", "Python Basics", 0.8),
    ("Pandas", "NumPy", 0.6),
    ("Data Visualization", "Pandas", 0.8),
    ("Data Cleaning", "Pandas", 0.9),
    ("Exploratory Data Analysis", "Pandas", 0.8),
    ("Exploratory Data Analysis", "Data Visualization", 0.7),
    ("Inferential Statistics", "Probability", 0.9),
    ("Inferential Statistics", "Descriptive Statistics", 0.7),
    ("Apache Spark & Distributed Computing", "Python Intermediate", 0.7),
    ("ML Fundamentals", "Python Basics", 0.8),
    ("ML Fundamentals", "Descriptive Statistics", 0.7),
    ("Linear & Logistic Regression", "ML Fundamentals", 1.0),
    ("Linear & Logistic Regression", "Linear Algebra", 0.8),
    ("Decision Trees & Ensemble Methods", "ML Fundamentals", 0.9),
    ("Model Evaluation & Tuning", "ML Fundamentals", 1.0),
    ("Feature Engineering", "Pandas", 0.8),
    ("Neural Networks Basics", "Linear Algebra", 0.8),
    ("Neural Networks Basics", "Calculus", 0.8),
    ("Deep Learning with PyTorch", "Neural Networks Basics", 1.0),
    ("Computer Vision & CNNs", "Deep Learning with PyTorch", 1.0),
    ("Natural Language Processing", "Deep Learning with PyTorch", 1.0),
    ("Transformers & LLM Engineering", "Natural Language Processing", 1.0),
    ("Vector Databases & Semantic Search", "Transformers & LLM Engineering", 0.9),

    # DevOps & Cloud
    ("Container Networking & Storage", "Docker Basics", 1.0),
    ("CI/CD Pipelines", "Git & Version Control", 0.9),
    ("CI/CD Pipelines", "Docker Basics", 0.8),
    ("Kubernetes Orchestration", "Docker Basics", 1.0),
    ("Kubernetes Orchestration", "Container Networking & Storage", 0.9),
    ("Infrastructure as Code (Terraform)", "AWS Cloud Foundations", 0.8),
    ("Site Reliability & Monitoring", "Linux Command Line", 0.8),
    ("Model Deployment & MLOps", "Docker Basics", 0.9),
    ("Model Deployment & MLOps", "ML Fundamentals", 0.8),

    # CS & Security
    ("Algorithms (Sorting, Searching, Graphs)", "Data Structures (Arrays, Lists, Trees)", 1.0),
    ("Ethical Hacking & Web Security", "Computer Networks & Protocols", 0.8),
    ("Security Auditing & Hardening", "Linux Command Line", 0.9),
    ("Security Auditing & Hardening", "Network Security & Cryptography", 0.8),

    # Web3 & Hardware
    ("Web3 & Decentralized Apps", "Solidity & Smart Contracts", 0.9),
    ("IoT Protocols & Edge Computing", "Embedded Systems & Microcontrollers", 0.8),
    ("Figma & Design Systems", "UI/UX Design & Wireframing", 1.0),
]

# Comprehensive Role Presets for distinct domains
CATALOG_ROLE_PRESETS = {
    # --- PROGRAMMING ---
    "Python Developer": [
        ("Python Basics", 95, 1.0),
        ("Python Intermediate", 90, 1.0),
        ("Python Advanced", 85, 0.9),
        ("Git & Version Control", 85, 0.8),
        ("Linux Command Line", 80, 0.7),
        ("Docker Basics", 75, 0.6),
        ("Technical Communication", 75, 0.5),
    ],
    "Java Developer": [
        ("Java Fundamentals", 95, 1.0),
        ("Java OOP & Collections", 90, 1.0),
        ("SQL Fundamentals", 85, 0.8),
        ("RESTful API Design", 85, 0.8),
        ("Spring Boot & Enterprise Java", 90, 0.9),
        ("Microservices Architecture", 80, 0.8),
        ("Git & Version Control", 80, 0.7),
        ("Test Automation & QA", 80, 0.7),
        ("Docker Basics", 75, 0.6),
    ],
    "C Developer": [
        ("C Programming Basics", 95, 1.0),
        ("Pointers & Memory Management", 95, 1.0),
        ("Data Structures (Arrays, Lists, Trees)", 85, 0.9),
        ("Linux Command Line", 85, 0.8),
        ("Git & Version Control", 80, 0.7),
    ],
    "C++ Developer": [
        ("C Programming Basics", 90, 0.9),
        ("C++ Fundamentals", 95, 1.0),
        ("Modern C++ & STL", 90, 1.0),
        ("Data Structures (Arrays, Lists, Trees)", 85, 0.8),
        ("Linux Command Line", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "C# & .NET Developer": [
        ("C# Basics & OOP", 95, 1.0),
        (".NET Core & ASP.NET", 90, 1.0),
        ("SQL Fundamentals", 85, 0.8),
        ("RESTful API Design", 85, 0.8),
        ("Git & Version Control", 80, 0.7),
    ],
    "JavaScript Developer": [
        ("HTML Fundamentals", 90, 0.9),
        ("CSS Fundamentals", 90, 0.9),
        ("JavaScript Fundamentals", 95, 1.0),
        ("Modern ES6+ & Async JS", 95, 1.0),
        ("DOM & Browser APIs", 90, 0.9),
        ("Git & Version Control", 80, 0.7),
    ],
    "TypeScript Developer": [
        ("JavaScript Fundamentals", 90, 0.9),
        ("Modern ES6+ & Async JS", 90, 0.9),
        ("TypeScript Fundamentals", 95, 1.0),
        ("Advanced TypeScript", 90, 0.9),
        ("Git & Version Control", 80, 0.7),
    ],
    "Go Developer": [
        ("Go Fundamentals", 95, 1.0),
        ("Go Concurrency & Goroutines", 90, 1.0),
        ("RESTful API Design", 85, 0.8),
        ("Docker Basics", 80, 0.7),
        ("Linux Command Line", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "Rust Developer": [
        ("Rust Syntax & Ownership", 95, 1.0),
        ("Rust Concurrency & Cargo", 90, 1.0),
        ("Data Structures (Arrays, Lists, Trees)", 85, 0.8),
        ("Linux Command Line", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "Kotlin Developer": [
        ("Kotlin Basics", 95, 1.0),
        ("Android Development with Kotlin", 90, 1.0),
        ("Java Fundamentals", 80, 0.7),
        ("RESTful API Design", 75, 0.6),
        ("Git & Version Control", 80, 0.7),
    ],
    "Swift Developer": [
        ("Swift Syntax & Basics", 95, 1.0),
        ("iOS Development with SwiftUI", 95, 1.0),
        ("RESTful API Design", 75, 0.6),
        ("Git & Version Control", 80, 0.7),
    ],
    "R Data Analyst": [
        ("R for Statistical Computing", 95, 1.0),
        ("Tidyverse & ggplot2", 90, 1.0),
        ("Descriptive Statistics", 85, 0.8),
        ("Inferential Statistics", 80, 0.8),
        ("Data Cleaning", 80, 0.7),
    ],
    "PHP & Laravel Developer": [
        ("PHP Fundamentals", 95, 1.0),
        ("Laravel Framework", 90, 1.0),
        ("SQL Fundamentals", 85, 0.8),
        ("HTML & CSS Responsive Layouts", 75, 0.6),
        ("Git & Version Control", 80, 0.7),
    ],

    # --- DATA & AI ---
    "Data Analyst": [
        ("SQL Fundamentals", 90, 1.0),
        ("SQL Advanced", 85, 0.9),
        ("Data Cleaning", 85, 0.9),
        ("Descriptive Statistics", 90, 0.9),
        ("Inferential Statistics", 80, 0.8),
        ("Python Basics", 80, 0.8),
        ("Pandas", 85, 0.9),
        ("Data Visualization", 90, 0.9),
        ("Exploratory Data Analysis", 85, 0.8),
        ("Power BI & Tableau Dashboarding", 85, 0.8),
        ("Technical Communication", 80, 0.7),
    ],
    "Data Scientist": [
        ("Python Basics", 90, 0.9),
        ("Linear Algebra", 80, 0.7),
        ("Descriptive Statistics", 85, 0.8),
        ("Inferential Statistics", 80, 0.8),
        ("NumPy", 85, 0.8),
        ("Pandas", 85, 0.8),
        ("Data Cleaning", 80, 0.8),
        ("ML Fundamentals", 85, 0.9),
        ("Linear & Logistic Regression", 85, 0.8),
        ("Model Evaluation & Tuning", 85, 0.8),
        ("Exploratory Data Analysis", 85, 0.8),
        ("Technical Communication", 80, 0.6),
    ],
    "Machine Learning Engineer": [
        ("Python Basics", 90, 0.9),
        ("Linear Algebra", 80, 0.8),
        ("Probability", 80, 0.8),
        ("NumPy", 85, 0.8),
        ("Pandas", 85, 0.8),
        ("ML Fundamentals", 90, 1.0),
        ("Linear & Logistic Regression", 85, 0.9),
        ("Decision Trees & Ensemble Methods", 85, 0.8),
        ("Model Evaluation & Tuning", 85, 0.9),
        ("Feature Engineering", 80, 0.8),
        ("Neural Networks Basics", 80, 0.8),
        ("Deep Learning with PyTorch", 75, 0.7),
        ("Model Deployment & MLOps", 75, 0.7),
    ],
    "AI Engineer": [
        ("Python Basics", 90, 0.9),
        ("Neural Networks Basics", 85, 0.8),
        ("Deep Learning with PyTorch", 85, 0.8),
        ("Natural Language Processing", 90, 0.9),
        ("Transformers & LLM Engineering", 95, 1.0),
        ("Vector Databases & Semantic Search", 90, 1.0),
        ("RESTful API Design", 80, 0.7),
        ("Model Deployment & MLOps", 80, 0.7),
    ],
    "Deep Learning Specialist": [
        ("Linear Algebra", 85, 0.9),
        ("Calculus", 80, 0.8),
        ("Neural Networks Basics", 95, 1.0),
        ("Deep Learning with PyTorch", 95, 1.0),
        ("Computer Vision & CNNs", 85, 0.8),
        ("Natural Language Processing", 85, 0.8),
    ],
    "NLP Engineer": [
        ("Python Basics", 90, 0.9),
        ("Natural Language Processing", 95, 1.0),
        ("Transformers & LLM Engineering", 95, 1.0),
        ("Vector Databases & Semantic Search", 85, 0.8),
        ("Deep Learning with PyTorch", 85, 0.8),
    ],
    "Computer Vision Engineer": [
        ("Python Basics", 90, 0.9),
        ("Linear Algebra", 85, 0.8),
        ("NumPy", 85, 0.8),
        ("Deep Learning with PyTorch", 90, 0.9),
        ("Computer Vision & CNNs", 95, 1.0),
    ],
    "Data Engineer": [
        ("SQL Fundamentals", 95, 1.0),
        ("SQL Advanced", 90, 1.0),
        ("Python Basics", 85, 0.8),
        ("ETL Pipelines & Data Warehousing", 95, 1.0),
        ("Apache Spark & Distributed Computing", 85, 0.9),
        ("Linux Command Line", 80, 0.7),
        ("Docker Basics", 75, 0.6),
    ],
    "Business Intelligence Developer": [
        ("SQL Fundamentals", 95, 1.0),
        ("SQL Advanced", 90, 0.9),
        ("Data Cleaning", 85, 0.8),
        ("Descriptive Statistics", 80, 0.7),
        ("Power BI & Tableau Dashboarding", 95, 1.0),
        ("Technical Communication", 80, 0.7),
    ],

    # --- SOFTWARE & WEB DEVELOPMENT ---
    "Full Stack Developer": [
        ("HTML Fundamentals", 95, 1.0),
        ("CSS Fundamentals", 95, 1.0),
        ("Responsive Design & CSS Layouts", 90, 0.9),
        ("JavaScript Fundamentals", 95, 1.0),
        ("Modern ES6+ & Async JS", 90, 0.9),
        ("DOM & Browser APIs", 90, 0.9),
        ("Git & Version Control", 85, 0.8),
        ("React Fundamentals", 95, 1.0),
        ("React State & Hooks", 90, 0.9),
        ("Backend Development", 90, 0.9),
        ("RESTful API Design", 90, 0.9),
        ("Databases & SQL", 85, 0.8),
        ("Authentication & Web Security", 85, 0.8),
        ("Test Automation & QA", 80, 0.7),
        ("Deployment & DevOps", 80, 0.7),
        ("Full-Stack Project Architecture", 85, 0.8),
    ],
    "Frontend Developer": [
        ("HTML Fundamentals", 95, 1.0),
        ("CSS Fundamentals", 95, 1.0),
        ("Responsive Design & CSS Layouts", 90, 0.9),
        ("JavaScript Fundamentals", 95, 1.0),
        ("Modern ES6+ & Async JS", 90, 0.9),
        ("DOM & Browser APIs", 90, 0.9),
        ("Git & Version Control", 80, 0.7),
        ("React Fundamentals", 95, 1.0),
        ("React State & Hooks", 90, 0.9),
        ("TypeScript Fundamentals", 85, 0.8),
    ],
    "Backend Developer": [
        ("Linux Command Line", 80, 0.7),
        ("Git & Version Control", 85, 0.8),
        ("Backend Development", 95, 1.0),
        ("RESTful API Design", 95, 1.0),
        ("Databases & SQL", 90, 0.9),
        ("SQL Advanced", 80, 0.8),
        ("Authentication & Web Security", 85, 0.8),
        ("Microservices Architecture", 85, 0.8),
        ("Docker Basics", 80, 0.7),
    ],
    "Web Developer": [
        ("HTML Fundamentals", 95, 1.0),
        ("CSS Fundamentals", 95, 1.0),
        ("Responsive Design & CSS Layouts", 90, 0.9),
        ("JavaScript Fundamentals", 90, 0.9),
        ("Modern ES6+ & Async JS", 85, 0.8),
        ("Git & Version Control", 80, 0.7),
        ("React Fundamentals", 85, 0.8),
        ("Databases & SQL", 80, 0.7),
    ],
    "Mobile App Developer": [
        ("Cross-Platform Flutter & Dart", 95, 1.0),
        ("RESTful API Design", 85, 0.8),
        ("Git & Version Control", 80, 0.7),
        ("JavaScript Fundamentals", 75, 0.6),
    ],
    "Android Developer": [
        ("Kotlin Basics", 95, 1.0),
        ("Android Development with Kotlin", 95, 1.0),
        ("RESTful API Design", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "iOS Developer": [
        ("Swift Syntax & Basics", 95, 1.0),
        ("iOS Development with SwiftUI", 95, 1.0),
        ("RESTful API Design", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "Game Developer": [
        ("Unity & C# Game Scripting", 95, 1.0),
        ("C# Basics & OOP", 90, 0.9),
        ("Unreal Engine & C++", 80, 0.8),
        ("Data Structures (Arrays, Lists, Trees)", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "Software Engineer": [
        ("Data Structures (Arrays, Lists, Trees)", 90, 1.0),
        ("Algorithms (Sorting, Searching, Graphs)", 90, 1.0),
        ("Software Design Patterns", 90, 0.9),
        ("System Design Fundamentals", 85, 0.8),
        ("Git & Version Control", 85, 0.8),
        ("Test Automation & QA", 80, 0.7),
    ],
    "API Developer": [
        ("RESTful API Design", 95, 1.0),
        ("GraphQL APIs", 90, 0.9),
        ("SQL Fundamentals", 85, 0.8),
        ("Microservices Architecture", 80, 0.8),
        ("Git & Version Control", 80, 0.7),
    ],

    # --- CLOUD & DEVOPS ---
    "DevOps Engineer": [
        ("Linux Command Line", 95, 1.0),
        ("Git & Version Control", 90, 0.9),
        ("Docker Basics", 95, 1.0),
        ("Container Networking & Storage", 90, 0.9),
        ("CI/CD Pipelines", 95, 1.0),
        ("Kubernetes Orchestration", 90, 0.9),
        ("Infrastructure as Code (Terraform)", 85, 0.8),
        ("AWS Cloud Foundations", 85, 0.8),
        ("Site Reliability & Monitoring", 85, 0.8),
        ("Network Security & Cryptography", 80, 0.7),
    ],
    "Docker & Container Specialist": [
        ("Linux Command Line", 90, 0.9),
        ("Docker Basics", 95, 1.0),
        ("Container Networking & Storage", 95, 1.0),
        ("CI/CD Pipelines", 85, 0.8),
        ("Kubernetes Orchestration", 90, 0.9),
    ],
    "Kubernetes Administrator": [
        ("Linux Command Line", 90, 0.9),
        ("Docker Basics", 90, 0.9),
        ("Container Networking & Storage", 90, 0.9),
        ("Kubernetes Orchestration", 95, 1.0),
        ("Site Reliability & Monitoring", 85, 0.8),
    ],
    "Cloud Engineer": [
        ("Linux Command Line", 90, 0.9),
        ("Docker Basics", 85, 0.8),
        ("AWS Cloud Foundations", 95, 1.0),
        ("Infrastructure as Code (Terraform)", 90, 0.9),
        ("CI/CD Pipelines", 85, 0.8),
        ("Computer Networks & Protocols", 80, 0.7),
    ],
    "AWS Cloud Architect": [
        ("AWS Cloud Foundations", 95, 1.0),
        ("Infrastructure as Code (Terraform)", 90, 0.9),
        ("Docker Basics", 85, 0.8),
        ("System Design Fundamentals", 85, 0.8),
        ("Network Security & Cryptography", 80, 0.7),
    ],
    "Microsoft Azure Specialist": [
        ("Microsoft Azure Foundations", 95, 1.0),
        ("Infrastructure as Code (Terraform)", 90, 0.9),
        ("Docker Basics", 85, 0.8),
        ("CI/CD Pipelines", 80, 0.7),
    ],
    "Google Cloud Engineer": [
        ("Google Cloud Platform (GCP)", 95, 1.0),
        ("Kubernetes Orchestration", 90, 0.9),
        ("Docker Basics", 85, 0.8),
        ("Infrastructure as Code (Terraform)", 85, 0.8),
    ],
    "Site Reliability Engineer (SRE)": [
        ("Linux Command Line", 95, 1.0),
        ("Site Reliability & Monitoring", 95, 1.0),
        ("Docker Basics", 85, 0.8),
        ("Kubernetes Orchestration", 85, 0.8),
        ("Computer Networks & Protocols", 80, 0.8),
        ("CI/CD Pipelines", 80, 0.7),
    ],

    # --- DATABASE / CS / CYBERSECURITY ---
    "SQL Developer": [
        ("SQL Fundamentals", 95, 1.0),
        ("SQL Advanced", 90, 1.0),
        ("Data Cleaning", 85, 0.8),
        ("Linux Command Line", 75, 0.7),
        ("Git & Version Control", 70, 0.6),
        ("Problem Formulation", 70, 0.5),
    ],
    "Database Administrator (DBA)": [
        ("SQL Fundamentals", 95, 1.0),
        ("SQL Advanced", 95, 1.0),
        ("Linux Command Line", 85, 0.8),
        ("Operating Systems & Concurrency", 80, 0.7),
        ("System Design Fundamentals", 80, 0.7),
    ],
    "Data Structures & Algorithms Specialist": [
        ("Data Structures (Arrays, Lists, Trees)", 95, 1.0),
        ("Algorithms (Sorting, Searching, Graphs)", 95, 1.0),
        ("Software Design Patterns", 85, 0.8),
        ("Problem Formulation", 85, 0.8),
        ("Technical Communication", 75, 0.7),
    ],
    "System Design Architect": [
        ("System Design Fundamentals", 95, 1.0),
        ("Computer Networks & Protocols", 90, 0.9),
        ("Microservices Architecture", 85, 0.8),
        ("SQL Advanced", 80, 0.7),
        ("Technical Communication", 85, 0.8),
    ],
    "Computer Networks Engineer": [
        ("Computer Networks & Protocols", 95, 1.0),
        ("Linux Command Line", 90, 0.9),
        ("Network Security & Cryptography", 85, 0.8),
        ("Operating Systems & Concurrency", 80, 0.7),
        ("Technical Communication", 75, 0.6),
    ],
    "Operating Systems Engineer": [
        ("Operating Systems & Concurrency", 95, 1.0),
        ("C Programming Basics", 90, 0.9),
        ("Pointers & Memory Management", 90, 0.9),
        ("Linux Command Line", 85, 0.8),
    ],
    "Cybersecurity Engineer": [
        ("Linux Command Line", 95, 1.0),
        ("Computer Networks & Protocols", 90, 0.9),
        ("Network Security & Cryptography", 95, 1.0),
        ("Ethical Hacking & Web Security", 90, 0.9),
        ("Security Auditing & Hardening", 85, 0.8),
        ("Git & Version Control", 80, 0.7),
    ],

    # --- SPECIALIZATIONS ---
    "Blockchain Developer": [
        ("Solidity & Smart Contracts", 95, 1.0),
        ("Web3 & Decentralized Apps", 90, 1.0),
        ("JavaScript Fundamentals", 85, 0.8),
        ("Network Security & Cryptography", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "Web3 Developer": [
        ("JavaScript Fundamentals", 90, 0.9),
        ("Modern ES6+ & Async JS", 85, 0.8),
        ("React Fundamentals", 85, 0.8),
        ("Solidity & Smart Contracts", 90, 1.0),
        ("Web3 & Decentralized Apps", 95, 1.0),
    ],
    "Embedded Systems Engineer": [
        ("C Programming Basics", 95, 1.0),
        ("Pointers & Memory Management", 90, 0.9),
        ("Embedded Systems & Microcontrollers", 95, 1.0),
        ("Operating Systems & Concurrency", 80, 0.7),
    ],
    "IoT Solutions Engineer": [
        ("Embedded Systems & Microcontrollers", 90, 0.9),
        ("IoT Protocols & Edge Computing", 95, 1.0),
        ("Python Basics", 85, 0.8),
        ("Computer Networks & Protocols", 80, 0.7),
    ],
    "Robotics Engineer": [
        ("Robotics & ROS", 95, 1.0),
        ("C++ Fundamentals", 90, 0.9),
        ("Python Basics", 85, 0.8),
        ("Linear Algebra", 80, 0.7),
    ],
    "QA & Test Automation Engineer": [
        ("JavaScript Fundamentals", 85, 0.8),
        ("Python Basics", 85, 0.8),
        ("Test Automation & QA", 95, 1.0),
        ("CI/CD Pipelines", 80, 0.7),
        ("Git & Version Control", 80, 0.7),
    ],
    "UI/UX Designer": [
        ("UI/UX Design & Wireframing", 95, 1.0),
        ("Figma & Design Systems", 95, 1.0),
        ("HTML & CSS Responsive Layouts", 75, 0.6),
        ("Technical Communication", 80, 0.7),
    ],
    "Product Manager": [
        ("Product Strategy & Management", 95, 1.0),
        ("Problem Formulation", 90, 0.9),
        ("Technical Communication", 90, 0.9),
        ("Descriptive Statistics", 75, 0.6),
    ],
}
